//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahantExport.GIADownload {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.reportcheck.model.ngs.com/", ConfigurationName="GIADownload.ReportCheckWS")]
    public interface ReportCheckWS {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MahantExport.GIADownload.processRequestResponse processRequest(MahantExport.GIADownload.processRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MahantExport.GIADownload.processRequestResponse> processRequestAsync(MahantExport.GIADownload.processRequestRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MahantExport.GIADownload.getReportCheckDateResultResponse getReportCheckDateResult(MahantExport.GIADownload.getReportCheckDateResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MahantExport.GIADownload.getReportCheckDateResultResponse> getReportCheckDateResultAsync(MahantExport.GIADownload.getReportCheckDateResultRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MahantExport.GIADownload.downloadPDFReportResponse downloadPDFReport(MahantExport.GIADownload.downloadPDFReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MahantExport.GIADownload.downloadPDFReportResponse> downloadPDFReportAsync(MahantExport.GIADownload.downloadPDFReportRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MahantExport.GIADownload.processRequest1Response processRequest1(MahantExport.GIADownload.processRequest1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MahantExport.GIADownload.processRequest1Response> processRequest1Async(MahantExport.GIADownload.processRequest1Request request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MahantExport.GIADownload.getColoredStonePearlResultsResponse getColoredStonePearlResults(MahantExport.GIADownload.getColoredStonePearlResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MahantExport.GIADownload.getColoredStonePearlResultsResponse> getColoredStonePearlResultsAsync(MahantExport.GIADownload.getColoredStonePearlResultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processRequest", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.processRequestRequestBody Body;
        
        public processRequestRequest() {
        }
        
        public processRequestRequest(MahantExport.GIADownload.processRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class processRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public processRequestRequestBody() {
        }
        
        public processRequestRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processRequestResponse", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.processRequestResponseBody Body;
        
        public processRequestResponse() {
        }
        
        public processRequestResponse(MahantExport.GIADownload.processRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class processRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public processRequestResponseBody() {
        }
        
        public processRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportCheckDateResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportCheckDateResult", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.getReportCheckDateResultRequestBody Body;
        
        public getReportCheckDateResultRequest() {
        }
        
        public getReportCheckDateResultRequest(MahantExport.GIADownload.getReportCheckDateResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getReportCheckDateResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getReportCheckDateResultRequestBody() {
        }
        
        public getReportCheckDateResultRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportCheckDateResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportCheckDateResultResponse", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.getReportCheckDateResultResponseBody Body;
        
        public getReportCheckDateResultResponse() {
        }
        
        public getReportCheckDateResultResponse(MahantExport.GIADownload.getReportCheckDateResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getReportCheckDateResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getReportCheckDateResultResponseBody() {
        }
        
        public getReportCheckDateResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFReport", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.downloadPDFReportRequestBody Body;
        
        public downloadPDFReportRequest() {
        }
        
        public downloadPDFReportRequest(MahantExport.GIADownload.downloadPDFReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadPDFReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public downloadPDFReportRequestBody() {
        }
        
        public downloadPDFReportRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFReportResponse", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.downloadPDFReportResponseBody Body;
        
        public downloadPDFReportResponse() {
        }
        
        public downloadPDFReportResponse(MahantExport.GIADownload.downloadPDFReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class downloadPDFReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] @return;
        
        public downloadPDFReportResponseBody() {
        }
        
        public downloadPDFReportResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processRequest1", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.processRequest1RequestBody Body;
        
        public processRequest1Request() {
        }
        
        public processRequest1Request(MahantExport.GIADownload.processRequest1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class processRequest1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public processRequest1RequestBody() {
        }
        
        public processRequest1RequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processRequest1Response", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.processRequest1ResponseBody Body;
        
        public processRequest1Response() {
        }
        
        public processRequest1Response(MahantExport.GIADownload.processRequest1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class processRequest1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public processRequest1ResponseBody() {
        }
        
        public processRequest1ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getColoredStonePearlResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getColoredStonePearlResults", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.getColoredStonePearlResultsRequestBody Body;
        
        public getColoredStonePearlResultsRequest() {
        }
        
        public getColoredStonePearlResultsRequest(MahantExport.GIADownload.getColoredStonePearlResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getColoredStonePearlResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getColoredStonePearlResultsRequestBody() {
        }
        
        public getColoredStonePearlResultsRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getColoredStonePearlResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getColoredStonePearlResultsResponse", Namespace="http://service.reportcheck.model.ngs.com/", Order=0)]
        public MahantExport.GIADownload.getColoredStonePearlResultsResponseBody Body;
        
        public getColoredStonePearlResultsResponse() {
        }
        
        public getColoredStonePearlResultsResponse(MahantExport.GIADownload.getColoredStonePearlResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getColoredStonePearlResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getColoredStonePearlResultsResponseBody() {
        }
        
        public getColoredStonePearlResultsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportCheckWSChannel : MahantExport.GIADownload.ReportCheckWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportCheckWSClient : System.ServiceModel.ClientBase<MahantExport.GIADownload.ReportCheckWS>, MahantExport.GIADownload.ReportCheckWS {
        
        public ReportCheckWSClient() {
        }
        
        public ReportCheckWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportCheckWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportCheckWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportCheckWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MahantExport.GIADownload.processRequestResponse MahantExport.GIADownload.ReportCheckWS.processRequest(MahantExport.GIADownload.processRequestRequest request) {
            return base.Channel.processRequest(request);
        }
        
        public string processRequest(string arg0) {
            MahantExport.GIADownload.processRequestRequest inValue = new MahantExport.GIADownload.processRequestRequest();
            inValue.Body = new MahantExport.GIADownload.processRequestRequestBody();
            inValue.Body.arg0 = arg0;
            MahantExport.GIADownload.processRequestResponse retVal = ((MahantExport.GIADownload.ReportCheckWS)(this)).processRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MahantExport.GIADownload.processRequestResponse> MahantExport.GIADownload.ReportCheckWS.processRequestAsync(MahantExport.GIADownload.processRequestRequest request) {
            return base.Channel.processRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MahantExport.GIADownload.processRequestResponse> processRequestAsync(string arg0) {
            MahantExport.GIADownload.processRequestRequest inValue = new MahantExport.GIADownload.processRequestRequest();
            inValue.Body = new MahantExport.GIADownload.processRequestRequestBody();
            inValue.Body.arg0 = arg0;
            return ((MahantExport.GIADownload.ReportCheckWS)(this)).processRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MahantExport.GIADownload.getReportCheckDateResultResponse MahantExport.GIADownload.ReportCheckWS.getReportCheckDateResult(MahantExport.GIADownload.getReportCheckDateResultRequest request) {
            return base.Channel.getReportCheckDateResult(request);
        }
        
        public string getReportCheckDateResult(string arg0) {
            MahantExport.GIADownload.getReportCheckDateResultRequest inValue = new MahantExport.GIADownload.getReportCheckDateResultRequest();
            inValue.Body = new MahantExport.GIADownload.getReportCheckDateResultRequestBody();
            inValue.Body.arg0 = arg0;
            MahantExport.GIADownload.getReportCheckDateResultResponse retVal = ((MahantExport.GIADownload.ReportCheckWS)(this)).getReportCheckDateResult(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MahantExport.GIADownload.getReportCheckDateResultResponse> MahantExport.GIADownload.ReportCheckWS.getReportCheckDateResultAsync(MahantExport.GIADownload.getReportCheckDateResultRequest request) {
            return base.Channel.getReportCheckDateResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<MahantExport.GIADownload.getReportCheckDateResultResponse> getReportCheckDateResultAsync(string arg0) {
            MahantExport.GIADownload.getReportCheckDateResultRequest inValue = new MahantExport.GIADownload.getReportCheckDateResultRequest();
            inValue.Body = new MahantExport.GIADownload.getReportCheckDateResultRequestBody();
            inValue.Body.arg0 = arg0;
            return ((MahantExport.GIADownload.ReportCheckWS)(this)).getReportCheckDateResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MahantExport.GIADownload.downloadPDFReportResponse MahantExport.GIADownload.ReportCheckWS.downloadPDFReport(MahantExport.GIADownload.downloadPDFReportRequest request) {
            return base.Channel.downloadPDFReport(request);
        }
        
        public byte[] downloadPDFReport(string arg0) {
            MahantExport.GIADownload.downloadPDFReportRequest inValue = new MahantExport.GIADownload.downloadPDFReportRequest();
            inValue.Body = new MahantExport.GIADownload.downloadPDFReportRequestBody();
            inValue.Body.arg0 = arg0;
            MahantExport.GIADownload.downloadPDFReportResponse retVal = ((MahantExport.GIADownload.ReportCheckWS)(this)).downloadPDFReport(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MahantExport.GIADownload.downloadPDFReportResponse> MahantExport.GIADownload.ReportCheckWS.downloadPDFReportAsync(MahantExport.GIADownload.downloadPDFReportRequest request) {
            return base.Channel.downloadPDFReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<MahantExport.GIADownload.downloadPDFReportResponse> downloadPDFReportAsync(string arg0) {
            MahantExport.GIADownload.downloadPDFReportRequest inValue = new MahantExport.GIADownload.downloadPDFReportRequest();
            inValue.Body = new MahantExport.GIADownload.downloadPDFReportRequestBody();
            inValue.Body.arg0 = arg0;
            return ((MahantExport.GIADownload.ReportCheckWS)(this)).downloadPDFReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MahantExport.GIADownload.processRequest1Response MahantExport.GIADownload.ReportCheckWS.processRequest1(MahantExport.GIADownload.processRequest1Request request) {
            return base.Channel.processRequest1(request);
        }
        
        public string processRequest1(string arg0) {
            MahantExport.GIADownload.processRequest1Request inValue = new MahantExport.GIADownload.processRequest1Request();
            inValue.Body = new MahantExport.GIADownload.processRequest1RequestBody();
            inValue.Body.arg0 = arg0;
            MahantExport.GIADownload.processRequest1Response retVal = ((MahantExport.GIADownload.ReportCheckWS)(this)).processRequest1(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MahantExport.GIADownload.processRequest1Response> MahantExport.GIADownload.ReportCheckWS.processRequest1Async(MahantExport.GIADownload.processRequest1Request request) {
            return base.Channel.processRequest1Async(request);
        }
        
        public System.Threading.Tasks.Task<MahantExport.GIADownload.processRequest1Response> processRequest1Async(string arg0) {
            MahantExport.GIADownload.processRequest1Request inValue = new MahantExport.GIADownload.processRequest1Request();
            inValue.Body = new MahantExport.GIADownload.processRequest1RequestBody();
            inValue.Body.arg0 = arg0;
            return ((MahantExport.GIADownload.ReportCheckWS)(this)).processRequest1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MahantExport.GIADownload.getColoredStonePearlResultsResponse MahantExport.GIADownload.ReportCheckWS.getColoredStonePearlResults(MahantExport.GIADownload.getColoredStonePearlResultsRequest request) {
            return base.Channel.getColoredStonePearlResults(request);
        }
        
        public string getColoredStonePearlResults(string arg0) {
            MahantExport.GIADownload.getColoredStonePearlResultsRequest inValue = new MahantExport.GIADownload.getColoredStonePearlResultsRequest();
            inValue.Body = new MahantExport.GIADownload.getColoredStonePearlResultsRequestBody();
            inValue.Body.arg0 = arg0;
            MahantExport.GIADownload.getColoredStonePearlResultsResponse retVal = ((MahantExport.GIADownload.ReportCheckWS)(this)).getColoredStonePearlResults(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MahantExport.GIADownload.getColoredStonePearlResultsResponse> MahantExport.GIADownload.ReportCheckWS.getColoredStonePearlResultsAsync(MahantExport.GIADownload.getColoredStonePearlResultsRequest request) {
            return base.Channel.getColoredStonePearlResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MahantExport.GIADownload.getColoredStonePearlResultsResponse> getColoredStonePearlResultsAsync(string arg0) {
            MahantExport.GIADownload.getColoredStonePearlResultsRequest inValue = new MahantExport.GIADownload.getColoredStonePearlResultsRequest();
            inValue.Body = new MahantExport.GIADownload.getColoredStonePearlResultsRequestBody();
            inValue.Body.arg0 = arg0;
            return ((MahantExport.GIADownload.ReportCheckWS)(this)).getColoredStonePearlResultsAsync(inValue);
        }
    }
}
